// import { counterConstants } from "../action/constants";

// const initialState = {
//   user: {
//     name: "shan",
//     task: "namaz",
//   },
// };
const initialState = [
  {
    name: "Matthew Jackson",
    sign: "./images/content/cup.svg",
    number: "1",
    url: "/profile",
    color: "#3772FF",
    avatar: "./images/icons/icon37.png",
    reward: "./images/content/reward-1.svg",
    price: "2.456",
    icon: "bsc.png",
    isVerified: true,
    isOnline: false,
    bscPP: [0.12, "+5%"],
    ethPP: [0.11, "+10%"],
    polygonPP: [0.32, "+15%"],
  },
  {
    name: "Jhonson",
    sign: "./images/content/donut.svg",
    number: "2",
    url: "/profile",
    color: "#9757D7",
    avatar: "./images/icons/icon38.png",
    reward: "./images/content/reward-1.svg",
    price: "2.456",
    icon: "bsc.png",
    isVerified: false,
    isOnline: false,
    bscPerc: "+3%",
    ethPerc: "+4%",
    polygonPerc: "+10%",
    bscPP: [0.12, "+3%"],
    ethPP: [0.22, "+4%"],
    polygonPP: [0.37, "+10%"],
  },
  {
    name: "Katrina Martinez",
    sign: "./images/content/lightning.svg",
    number: "3",
    url: "/profile",
    color: "#45B26B",
    avatar: "./images/icons/icon44.png",
    reward: "./images/content/reward-1.svg",
    price: "2.456",
    icon: "bsc.png",
    isVerified: false,
    isOnline: true,
    bscPerc: "+6%",
    ethPerc: "+4%",
    polygonPerc: "+9%",
    bscPP: [0.12, "+6%"],
    ethPP: [0.14, "+4%"],
    polygonPP: [0.27, "+9%"],
  },
  {
    name: "Hunter Ray",
    sign: "./images/content/donut.svg",
    number: "4",
    url: "/profile",
    color: "#23262F",
    avatar: "./images/icons/icon45.png",
    reward: "./images/content/reward-1.svg",
    price: "2.456",
    icon: "ethereum.png",
    isVerified: true,
    isOnline: true,
    bscPerc: "+2%",
    ethPerc: "+1%",
    polygonPerc: "+15%",
    bscPP: [0.19, "+2%"],
    ethPP: [0.09, "+1%"],
    polygonPP: [0.21, "+15%"],
  },
  {
    name: "Elizabeth Rivas",
    sign: "./images/content/donut.svg",
    number: "5",
    url: "/profile",
    color: "#777E90",
    avatar: "./images/icons/icon41.png",
    reward: "./images/content/reward-1.svg",
    price: "2.456",
    icon: "ethereum.png",
    isVerified: true,
    isOnline: false,
    bscPerc: "+4%",
    ethPerc: "+7%",
    polygonPerc: "+13%",
    bscPP: [0.12, "+4%"],
    ethPP: [0.17, "+7%"],
    polygonPP: [0.22, "+13%"],
  },
  {
    name: "Edd Harris",
    sign: "./images/content/cup.svg",
    number: "1",
    url: "/profile",
    color: "#3772FF",
    avatar: "./images/icons/icon42.png",
    reward: "./images/content/reward-1.svg",
    price: "2.456",
    icon: "salona.svg",
    isVerified: false,
    isOnline: false,
    bscPerc: "+7%",
    ethPerc: "+9%",
    polygonPerc: "+20%",
    bscPP: [0.12, "+7%"],
    ethPP: [0.1, "+9%"],
    polygonPP: [0.32, "+20%"],
  },
  {
    name: "Jhonson",
    sign: "./images/content/donut.svg",
    number: "2",
    url: "/profile",
    color: "#9757D7",
    avatar: "./images/icons/icon43.png",
    reward: "./images/content/reward-1.svg",
    price: "2.456",
    icon: "ethereum.png",
    isVerified: true,
    isOnline: true,
    bscPerc: "+1%",
    ethPerc: "+7%",
    polygonPerc: "+17%",
    bscPP: [0.12, "+1%"],
    ethPP: [0.13, "+7%"],
    polygonPP: [0.12, "+17%"],
  },
  {
    name: "Katrina Martinez",
    sign: "./images/content/lightning.svg",
    number: "3",
    url: "/profile",
    color: "#45B26B",
    avatar: "./images/icons/icon44.png",
    reward: "./images/content/reward-1.svg",
    price: "2.456",
    icon: "salona.svg",
    isVerified: true,
    isOnline: true,
    bscPerc: "+9%",
    ethPerc: "+13%",
    polygonPerc: "+20%",
    bscPP: [0.12, "+9%"],
    ethPP: [0.15, "+13%"],
    polygonPP: [0.52, "+20%"],
  },
];
const itemsReducer = (state = initialState, action) => {
  switch (action.type) {
    // case counterConstants.INCREMENT:
    //   return state + 1;
    // state = {
    //   ...\\,
    // };
    default:
      return state;
  }
};
export default itemsReducer;
