export const fetchMyCollectionConstants = {
  FETCH_MYCOLLECTION_DATA_REQUEST: "FETCH_MYCOLLECTION_DATA_REQUEST",
  FETCH_MYCOLLECTION_DATA_SUCCESS: "FETCH_MYCOLLECTION_DATA_SUCCESS",
  FETCH_MYCOLLECTION_DATA_FAILURE: "FETCH_MYCOLLECTION_DATA_FAILURE",
};

export const fetchCollectionNamesConstants = {
  FETCH_COLLECTION_NAMES_REQUEST: "FETCH_COLLECTION_NAMES_REQUEST",
  FETCH_COLLECTION_NAMES_SUCCESS: "FETCH_COLLECTION_NAMES_SUCCESS",
  FETCH_COLLECTION_NAMES_FAILURE: "FETCH_COLLECTION_NAMES_FAILURE",
};

export const fetchCollectionConstants = {
  FETCH_COLLECTION_REQUEST: "FETCH_COLLECTION_REQUEST",
  FETCH_COLLECTION_SUCCESS: "FETCH_COLLECTION_SUCCESS",
  FETCH_COLLECTION_FAILURE: "FETCH_COLLECTION_FAILURE",
};

export const deleteCollectionConstants = {
  DELETE_COLLECTION_REQUEST: "DELETE_COLLECTION_REQUEST",
  DELETE_COLLECTION_SUCCESS: "DELETE_COLLECTION_SUCCESS",
  DELETE_COLLECTION_FAILURE: "DELETE_COLLECTION_FAILURE",
};
