export const user = [
  {
    id: 1,
    username: "Enrico Cole",
    link: "0xc4c16a645...b21a",
    bio: "A wholesome farm owner in Montana. Upcoming gallery solo show in Germany",
    image: "../images/icons/icon46.png",
    followers: [
      {
        name: "Sally Fadel",
        counter: "161 followers",
        avatar: "../images/icons/icon48.png",
        // url: "",
        buttonClass: "blue",
        buttonContent: "Follow",
        gallery: [
          "../images/content/pic1.png",
          "../images/content/pic2.png",
          "../images/content/pic3.png",
          "../images/content/pic4.png",
        ],
      },
      {
        name: "Aniya Harber",
        counter: "161 followers",
        avatar: "../images/icons/icon47.png",
        // url: "",
        buttonClass: "blue",
        buttonContent: "Follow",
        gallery: [
          "./images/content/pic1.png",
          "./images/content/pic2.png",
          "./images/content/pic3.png",
          "./images/content/pic4.png",
        ],
      },
      {
        name: "Edwardo Bea",
        counter: "161 followers",
        avatar: "./images/icons/icon46.png",
        // url: "",
        buttonClass: "blue",
        buttonContent: "Follow",
        gallery: [
          "./images/content/pic1.png",
          "./images/content/pic2.png",
          "./images/content/pic3.png",
          "./images/content/pic4.png",
        ],
      },
      {
        name: "Reymundo",
        counter: "161 followers",
        avatar: "./images/icons/icon45.png",
        // url: "",
        buttonClass: "blue",
        buttonContent: "Follow",
        gallery: [
          "./images/content/pic1.png",
          "./images/content/pic2.png",
          "./images/content/pic3.png",
          "./images/content/pic4.png",
        ],
      },
      {
        name: "Jeanette",
        counter: "161 followers",
        avatar: "./images/icons/icon44.png",
        // url: "",
        buttonClass: "blue",
        buttonContent: "Follow",
        gallery: [
          "./images/content/pic1.png",
          "./images/content/pic2.png",
          "./images/content/pic3.png",
          "./images/content/pic4.png",
        ],
      },
    ],
  },
  {
    id: 2,
    username: "Enrico Cole",
    link: "0xc4c16a645...b21a",
    bio: "A wholesome farm owner in Montana. Upcoming gallery solo show in Germany",
    image: "/images/icons/icon45.png",
    followers: [
      {
        name: "Sally Fadel",
        counter: "161 followers",
        avatar: "./images/icons/icon48.png",
        // url: "",
        buttonClass: "blue",
        buttonContent: "Follow",
        gallery: [
          "./images/content/pic1.png",
          "./images/content/pic2.png",
          "./images/content/pic3.png",
          "./images/content/pic4.png",
        ],
      },
      {
        name: "Aniya Harber",
        counter: "161 followers",
        avatar: "./images/icons/icon47.png",
        // url: "",
        buttonClass: "blue",
        buttonContent: "Follow",
        gallery: [
          "./images/content/pic1.png",
          "./images/content/pic2.png",
          "./images/content/pic3.png",
          "./images/content/pic4.png",
        ],
      },
      {
        name: "Edwardo Bea",
        counter: "161 followers",
        avatar: "./images/icons/icon46.png",
        // url: "",
        buttonClass: "blue",
        buttonContent: "Follow",
        gallery: [
          "./images/content/pic1.png",
          "./images/content/pic2.png",
          "./images/content/pic3.png",
          "./images/content/pic4.png",
        ],
      },
      {
        name: "Reymundo",
        counter: "161 followers",
        avatar: "./images/icons/icon45.png",
        // url: "",
        buttonClass: "blue",
        buttonContent: "Follow",
        gallery: [
          "./images/content/pic1.png",
          "./images/content/pic2.png",
          "./images/content/pic3.png",
          "./images/content/pic4.png",
        ],
      },
      {
        name: "Jeanette",
        counter: "161 followers",
        avatar: "./images/icons/icon44.png",
        // url: "",
        buttonClass: "blue",
        buttonContent: "Follow",
        gallery: [
          "./images/content/pic1.png",
          "./images/content/pic2.png",
          "./images/content/pic3.png",
          "./images/content/pic4.png",
        ],
      },
    ],
  },
];

// export const followers = [
//   {
//     name: "Sally Fadel",
//     counter: "161 followers",
//     avatar: "./images/icons/icon48.png",
//     // url: "",
//     buttonClass: "blue",
//     buttonContent: "Follow",
//     gallery: [
//       "./images/content/pic1.png",
//       "./images/content/pic2.png",
//       "./images/content/pic3.png",
//       "./images/content/pic4.png",
//     ],
//   },
//   {
//     name: "Aniya Harber",
//     counter: "161 followers",
//     avatar: "./images/icons/icon47.png",
//     // url: "",
//     buttonClass: "blue",
//     buttonContent: "Follow",
//     gallery: [
//       "./images/content/pic1.png",
//       "./images/content/pic2.png",
//       "./images/content/pic3.png",
//       "./images/content/pic4.png",
//     ],
//   },
//   {
//     name: "Edwardo Bea",
//     counter: "161 followers",
//     avatar: "./images/icons/icon46.png",
//     // url: "",
//     buttonClass: "blue",
//     buttonContent: "Follow",
//     gallery: [
//       "./images/content/pic1.png",
//       "./images/content/pic2.png",
//       "./images/content/pic3.png",
//       "./images/content/pic4.png",
//     ],
//   },
//   {
//     name: "Reymundo",
//     counter: "161 followers",
//     avatar: "./images/icons/icon45.png",
//     // url: "",
//     buttonClass: "blue",
//     buttonContent: "Follow",
//     gallery: [
//       "./images/content/pic1.png",
//       "./images/content/pic2.png",
//       "./images/content/pic3.png",
//       "./images/content/pic4.png",
//     ],
//   },
//   {
//     name: "Jeanette",
//     counter: "161 followers",
//     avatar: "./images/icons/icon44.png",
//     // url: "",
//     buttonClass: "blue",
//     buttonContent: "Follow",
//     gallery: [
//       "./images/content/pic1.png",
//       "./images/content/pic2.png",
//       "./images/content/pic3.png",
//       "./images/content/pic4.png",
//     ],
//   },
// ];
